version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
      - ./conf:/etc/nginx/conf.d:ro
    
    ports:
      - "80:80"
      - "443:443"

